--Con dos guiones podemos escribir comentario
/*
Comentarios de 
multiples 
lineas

SQL lenguaje de consultas estructurado Structured Query lenguage
Es un lenguaje para actualizar, obtener y calcular informacion en base de datos


Base de datos- conjunto de datos organizados entre si y que son almacenados
*/
--la estructura de las tablas queda de siguiente manera:
--toda tabla debe llevar llave primaria(primary key, ID)
--Puede llevar tambien llave doranea

--Tipo de datos (caracteres, numericos, tipo decha, etc)

--NUMBER-- datos numericos
--NVARCHAR2-- permite entrada de datos tipo caracter y alfanumericos
--NVARCHAR2--tiene la particularidad de liberar espacio de memoria
-- Por ejemplo podemos tener un dato declarado con 30 caracteres. Pero si no 
--se utilizan esos 30 caracteres, es espacio se libera.
--DATE--utilizados para menejo de fecha y hora
--DDL- data Definion Language- Creacion de regristro y manipulacion
--delos mismo

--SENTENCIA PARA LA CREACION DE TABLAS
-- VAMOS A CREAR UNA TABLA DE ALUMNOS

--EDAD. LA INFORMACION DEBE ESTAR CORRECTAMENTE DEFINIDA O ATOMIZADA.
--SEXO O GENERO
--GRADO DE ESTUDIOS
--STATUS(ACTIVO O INACTIVO)

CREATE TABLE ALUMNO(ID_ALUMNO NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(30),
FECHA DATE,
GENERO NVARCHAR2(10),
CURP NVARCHAR2(18),
GRADO NVARCHAR2(20),
STATUS NUMBER
);
--PARA VER LA ESTRUCTURA DE MI TABLA CON COMANDOS 
--SE UTLIZA DESCRIBE Y NOMBRE DE LA TABLA

DESCRIBE ALUMNO;

--CREATE UNA TABLA CON CARRERAS PARA LOS ALUMNOS
CREATE TABLE CARRERAS(
ID_CARRERA NUMBER PRIMARY KEY, 
NOMBRE NVARCHAR2(30),
AREA NVARCHAR2(30),
DURACION NUMBER,
NUM_MATERIAS NUMBER
);

DESCRIBE CARRERAS;
--RENOMBRAR UNA COLUMNA EN UNA TABLA
ALTER TABLE CARRERAS RENAME COLUMN NUM_MATERIAS TO MATERIAS;
--MODIFICAR EL TIPO DE DATOS EN LA COLUMNA (FUNCIONA SIEMPRE Y
--CUANDO NOSE TENGAN DATOS  EN ESA COLUMNA).
ALTER TABLE CARRERAS MODIFY DURACION NVARCHAR2(20);

--isercionde datos en nuestras tablas
--insertar datos en la tabla alumnos



DESCRIBE ALUMNO;
--CONSULTAR FORMATO DE FECHA DE MI SISTEMA
SELECT SYSDATE FROM DUAL;
INSERT INTO ALUMNO VALUES 
(1,'ESMERALDA','05/09/1990','FEMENINO','ESM900905MDF','8VO SEMESTRE',1);
INSERT INTO ALUMNO VALUES 
(2,'OSCAR','05/09/1995','MASCULINO','OSC900905MDF','7VO SEMESTRE',1);
INSERT INTO ALUMNO VALUES 
(3,'RAFAEL','05/09/1991','MASCULINO','RFM900905MDF','6VO SEMESTRE',1);

INSERT INTO ALUMNO VALUES 
(4,'EDUARDO','05/09/1996','MASCULINO','EDU900905MDF','9VO SEMESTRE',1);

INSERT INTO ALUMNO VALUES 
(5,'BENIGNO','05/09/1986','MASCULINO','BNG900905MDF','7VO SEMESTRE',1);

--REALIZAR UNA CONSULTA GENERAL DE LOS DATOS DE UNA TABLA
SELECT * FROM ALUMNO;
--ACTUALIZAR UN  DATO EN REGISTRO DETERMINADO 
    
select ALUMNO from user_tables order by table_name;

--REALIZAR UNA CONSULTA DE COLUMNAS ESPECIFICAS
SELECT NOMBRE FROM ALUMNO;

SELECT ID_ALUMNO, NOMBRE FROM ALUMNO;
-- COMO BORRAR UN REGISTRO ESPECIFICO DE UNA TABLA
DELETE FROM ALUMNO WHERE ID_ALUMNO=5;
--PARA CONFIRMAR CAMBIOS EN LOS REGISTROS

--INSERTAR REGRISTOS EN TABLA DE CARRARERAS
DESCRIBE CARRERAS;
INSERT INTO CARRERAS VALUES
(1,'ING EN SISTEMAS','EXACTAS','8VO SEMESTRES',50);

INSERT INTO CARRERAS VALUES
(2,'MEDICINA','BIOLOGICAS','10 SEMESTRES',90);
INSERT INTO CARRERAS VALUES
(3,'NUTRICION','BIOLOGICAS','8VO SEMESTRES',50);
INSERT INTO CARRERAS VALUES
(4,'DERECHO','HUMANIDADES','8VO SEMESTRES',50);
INSERT INTO CARRERAS VALUES
(5,'MERCADOTECNIA','ECONOMIA','8VO SEMESTRES',60);

SELECT * FROM CARRERAS;

--YA QUE TENOMES INFORMACION EN NUESTRAS DOS PRIMERAS TABLAS
--QUE SON ENTIDADES FUERTES
--PODEMOS AHORA SI LLEGAR O RELACIONAR LOS DATOS EN LA TABLA 
--CARRERAS ALUMNOS
COMMIT;

--IMSERTAMOS DATOS EN LA TABLA CARRERAS_ALUMNOS

DESCRIBE carreta_alumnos;

INSERT INTO CARRETA_ALUMNOS VALUES(1,1,5);
INSERT INTO CARRETA_ALUMNOS VALUES(2,2,4);
INSERT INTO CARRETA_ALUMNOS VALUES(3,3,1);
INSERT INTO CARRETA_ALUMNOS VALUES(4,4,2);


SELECT * FROM CARRETA_ALUMNOS;
COMMIT;
--COMO AGREGAR UNA COLUMNA A UNA TABLA
--COMO AGREGAR VALORES DECIMALES A UNA LOLUMNA

SELECT * FROM CARRERAS;

--ACTUALIZAR UN VALOR DE UN REGISTRO
UPDATE CARRERAS SET PRESUPUESTO=200000.99 WHERE ID_CARRERA=2;