CREATE TABLE ALUMNOS(
ID_ALUMNO NUMBER PRIMARY KEY ,
NOMBRE NVARCHAR2 (30),
FECHANAC DATE,
GENERO NVARCHAR2(10),
CURP NVARCHAR2(18),
GRADO NVARCHAR2(20),
STATUS NUMBER

);

CREATE TABLE CARRERA(
ID_CARRERA NUMBER PRIMARY KEY ,
NOMBRE NVARCHAR2(30),
AREA NVARCHAR2 (20),
DURACION NUMBER,
MATERIAS NUMBER

);


ALTER TABLE CARRERA MODIFY DURACION NVARCHAR2(20);


CREATE TABLE CARRERAS_ALUMNOS(
ID_CA NUMBER PRIMARY KEY ,
ID_ALUMNO NUMBER,
ID_CARRERA NUMBER

);



ALTER TABLE CARRERAS_ALUMNOS ADD CONSTRAINT FK_ID_ALUMNO
FOREIGN KEY (ID_ALUMNO)
REFERENCES ALUMNOS (ID_ALUMNO);

ALTER TABLE CARRERAS_ALUMNOS ADD CONSTRAINT FK_ID_CARRERA
FOREIGN KEY (ID_CARRERA)
REFERENCES CARRERA (ID_CARRERA);


ALTER TABLE ALUMNOS ADD CONSTRAINT CHECK_GENERO
CHECK (GENERO IN('MASCULINO','FEMENINO'));

ALTER TABLE CARRERA ADD CONSTRAINT UNQ_NOMBRE_CARRERA
UNIQUE (NOMBRE);


DESCRIBE ALUMNOS;
select sysDATE from dual;
INSERT INTO ALUMNOS VALUES
(1,'Esmeralda','05/SEP/90','FEMENINO','ESDADL123','8TAVO SEMESTRE',1);
INSERT INTO ALUMNOS VALUES
(2,'Oscar','05/SEP/90','MASCULINO','EIMDA123','8TAVO SEMESTRE',1);
INSERT INTO ALUMNOS VALUES
(3,'RAFAEL','05/SEP/90','MASCULINO','EFSDF34','8TAVO SEMESTRE',1);
INSERT INTO ALUMNOS VALUES
(4,'Eduardo','13/ene/97','MASCULINO','ASDASD3','8TAVO SEMESTRE',1);
INSERT INTO ALUMNOS VALUES
(5,'Benigno','05/SEP/90','MASCULINO','ERTREYR234','8TAVO SEMESTRE',1);


UPDATE alumnos SET fechanac='14/FEB/1982' WHERE id_alumno=2;
UPDATE alumnos SET CURP='OSC23443ASDEG' WHERE id_alumno=2;
DESCRIBE carrera;
INSERT INTO carrera VALUES
(1,'ING EN SISTEMAS','EXACTAS','8 SEMESTRES',50);
INSERT INTO carrera VALUES
(2,'MEDICINA','BIOLOGICAS','8 SEMESTRES',50);
INSERT INTO carrera VALUES
(3,'NUTRICION','BIOLOGICAS','8 SEMESTRES',50);
INSERT INTO carrera VALUES
(4,'DERECHO','HUMANIDADES','8 SEMESTRES',50);
INSERT INTO carrera VALUES
(5,'MERCADOTECNIA','ECONOMIA','8 SEMESTRES',50);
 

DELETE FROM alumnos  WHERE id_alumno=5;


DESCRIBE carreras_alumnos;

INSERT INTO carreras_alumnos VALUES
(1,1,5);
INSERT INTO carreras_alumnos VALUES
(2,2,4);
INSERT INTO carreras_alumnos VALUES
(3,3,1);
INSERT INTO carreras_alumnos VALUES
(4,4,2);
INSERT INTO carreras_alumnos VALUES
(5,5,3);


ALTER TABLE CARRERA ADD PRESUPUESTO NUMBER (5,2);
ALTER TABLE CARRERA MODIFY  PRESUPUESTO NUMBER (8,2);
SELECT* FROM CARRERA;
COMMIT;

--- creando ejemplos

CREATE TABLE TUTORES(
ID_TUTOR NUMBER PRIMARY KEY ,
NOMBRE_TUTOR NVARCHAR2 (30),

TELEFONO NVARCHAR2(10),
DIRECCION NVARCHAR2(18),
CLAVE NVARCHAR2(20)
);


CREATE TABLE ALUMNO_TUTOR(
ID_ALUMNO_TUTOR NUMBER PRIMARY KEY ,
ID_TUTOR NUMBER,
ID_ALUMNO NUMBER,
CONSTRAINT fk_ID_TUTOR FOREIGN KEY (ID_TUTOR) REFERENCES TUTORES (ID_TUTOR),
CONSTRAINT fk_ID_ALUMNO1 FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNOS(ID_ALUMNO)
);


COMMIT;
ALTER TABLE TUTORES ADD CONSTRAINT CHECK_CLAVE
CHECK (CLAVE IN('A','B','C','D'));

insert into TUTORES(ID_TUTOR,NOMBRE_TUTOR,TELEFONO,DIRECCION,CLAVE) VALUES
--(1,'PEDRO PICA PIEDRA','2221131112','28 DE NOVIEMBRE 19','D'),
--(2,'PABLO MARMOL','2221112314','CALLE 12 999','A')
--(3,'VERONICA GALINDO','5556641231','MOTERRAL 10','C')
--(4,'GUSTAVO TIJON','2221121112','ACAPULCO 21','B')
--(5,'EDUARDO CA.','4421131112','AV. PUEBLA 12','D')

;
describe alumnos;
DESCRIBE TUTORES;
DESCRIBE ALUMNO_TUTOR;

SELECT * FROM ALUMNO_TUTOR;

insert into ALUMNO_TUTOR(ID_ALUMNO_TUTOR,ID_TUTOR,ID_ALUMNO ) VALUES
--(1,1,1)
--(2,2,1)
--(3,3,5)
--(4,4,5)
--(5,5,3)
--(6,5,5)

;

INSERT ALL 
into ALUMNO_TUTOR(ID_ALUMNO_TUTOR,ID_TUTOR,ID_ALUMNO ) VALUES (1,1,1);
into ALUMNO_TUTOR(ID_ALUMNO_TUTOR,ID_TUTOR,ID_ALUMNO ) VALUES (3,3,5);

SELECT *FROM DUAL;

commit;


----Ejercicio TareA

CREATE TABLE PADRES(
ID_PADRES NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(40),
DIRECCION NVARCHAR2(40),
TELEFONO NVARCHAR2(10),
GENERO NVARCHAR2(20)
);

-- TABLA RELACIONAL

CREATE TABLE PADRES_ALUMNOS(
ID_PADRES_ALUMNOS NUMBER PRIMARY KEY,
ID_ALUMNO NUMBER,
ID_PADRES NUMBER,
CONSTRAINT fk_ID_PADRES FOREIGN KEY (ID_PADRES) REFERENCES PADRES (ID_PADRES),
CONSTRAINT fk_ID_ALUMNO_NFK FOREIGN KEY (ID_ALUMNO) REFERENCES alumnos (ID_ALUMNO)
);

ALTER TABLE PADRES ADD CONSTRAINT CHECK_GENERO2 CHECK (GENERO IN('MASCULINO','FEMENINO','NO BINARIO'));

INSERT ALL
INTO PADRES(ID_PADRES,NOMBRE,DIRECCION,TELEFONO,GENERO)VALUES (1,'OLAF LOPEZ','1 A SUR 1234','2221152637','MASCULINO')
INTO PADRES(ID_PADRES,NOMBRE,DIRECCION,TELEFONO,GENERO)VALUES (2,'PANCHO LOPEZ','HANNOVER 34','2222242626','MASCULINO')
INTO PADRES(ID_PADRES,NOMBRE,DIRECCION,TELEFONO,GENERO)VALUES (3,'MARIA ANTONIETA','1 A SUR 1234','2224141552','FEMENINO')
INTO PADRES(ID_PADRES,NOMBRE,DIRECCION,TELEFONO,GENERO)VALUES (4,'RONALDO DOSANTOS SAVEIRO','1 A SUR 1234','2212152337','MASCULINO')
INTO PADRES(ID_PADRES,NOMBRE,DIRECCION,TELEFONO,GENERO)VALUES (5,'ERLIN HALAN ','1 A SUR 1234','2225188510','MASCULINO')
SELECT *FROM DUAL;
SELECT* FROM PADRES;--_ALUMNOS;
INSERT ALL 
INTO PADRES_ALUMNOS (ID_PADRES_ALUMNOS,ID_ALUMNO,ID_PADRES)VALUES (1,1,4)
INTO PADRES_ALUMNOS (ID_PADRES_ALUMNOS,ID_ALUMNO,ID_PADRES)VALUES (2,4,3)
INTO PADRES_ALUMNOS (ID_PADRES_ALUMNOS,ID_ALUMNO,ID_PADRES)VALUES (3,4,1)
INTO PADRES_ALUMNOS (ID_PADRES_ALUMNOS,ID_ALUMNO,ID_PADRES)VALUES (4,4,2)
INTO PADRES_ALUMNOS (ID_PADRES_ALUMNOS,ID_ALUMNO,ID_PADRES)VALUES (5,3,1)
SELECT* FROM DUAL;
SELECT * FROM PADRES_ALUMNOS ;



CREATE SEQUENCE ALUMNO_SEQ
START WITH 6
INCREMENT BY 1
MAXVALUE 999
MINVALUE 1
NOCYCLE; 

CREATE TRIGGER INSERT_ID_ALUMNO
BEFORE INSERT ON ALUMNOS
FOR EACH ROW BEGIN 
SELECT ALUMNO_SEQ.NEXTVAL INTO:NEW.ID_ALUMNO FROM DUAL;
END;

CREATE SEQUENCE PROD_SEQ;
CREATE OR REPLACE TRIGGER ON_INSERT_PRODUCTO BEFORE 
INSERT ON PRODUCTOS FOR EACH ROW BEGIN
SELECT PROD_SEQ.NEXTVAL INTO :new.PRODUCTO_ID FROM dual;
END;


DROP TRIGGER INSERT_ID_ALUMNO;


SELECT * FROM ALUMNOS;
COMMIT;


DESCRIBE ALUMNOS;

INSERT INTO ALUMNOS VALUES(1,'ENRIQUE','24/JUN/1985','MASCULINO','MKASD123432','7MO SEMESTRE',1);

----

--Ejercicio 1 asuntos

CREATE TABLE CLIENTE(
DNI  NVARCHAR2(10) PRIMARY KEY,
NOMBRE NVARCHAR2(40),
DIRECCION NVARCHAR2(60),
TELEFONO NVARCHAR2(10),
CORREO NVARCHAR2(40)
);
CREATE TABLE PROCURADOR(
DNI  NVARCHAR2(10) PRIMARY KEY,
NOMBRE NVARCHAR2(40),
DIRECCION NVARCHAR2(60),
TELEFONO NVARCHAR2(10),
CORREO NVARCHAR2(40)
);

CREATE TABLE ASUNTOS(
NUMERO_DE_EXPEDIENTE  NUMBER PRIMARY KEY,
DNI_CLIENTE NVARCHAR2(10),
DNI_PROCURADOR NVARCHAR2(10),
FECHA_DE_INCIO DATE,
FECHA_DE_FINALIZACION DATE,
ESTADO NVARCHAR2(20),
CONSTRAINT fk_DNI_CLIENTE FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE (DNI),
CONSTRAINT fk_DNI_PROCURADOR FOREIGN KEY (DNI_PROCURADOR) REFERENCES PROCURADOR (DNI)
);

ALTER TABLE ASUNTOS ADD CONSTRAINT UNIQ_DNI_CLIENTE UNIQUE (DNI_CLIENTE);
ALTER TABLE ASUNTOS DROP CONSTRAINT  fk_DNI_PROCURADOR;
ALTER TABLE ASUNTOS DROP COLUMN DNI_PROCURADOR;
ALTER TABLE ASUNTOS ADD CONSTRAINT  CHECK_ESTADO CHECK (ESTADO IN ('INICIADO','EN TRAMITE','ARCHIVADO','FINALIZADO'));
ALTER TABLE ASUNTOS DROP CONSTRAINT CHECK_ESTADO;
CREATE SEQUENCE NUMERO_DE_EXPEDIENTE_SEQ;
CREATE OR REPLACE TRIGGER INSERT_NUMERO_DE_EXPEDIENTE BEFORE 
INSERT ON ASUNTOS FOR EACH ROW BEGIN
SELECT NUMERO_DE_EXPEDIENTE_SEQ.NEXTVAL INTO :new.NUMERO_DE_EXPEDIENTE FROM dual;
END;

DESCRIBE CLIENTE;
INSERT ALL
INTO CLIENTE (DNI,NOMBRE,DIRECCION,TELEFONO,CORREO) VALUES ('00523821F','mARCELO DE LA VEGA CONSTANTINO','28 DE JUNIO 128','1234567890','MARCELO.DKA@GMAIL.COM')
INTO CLIENTE (DNI,NOMBRE,DIRECCION,TELEFONO,CORREO) VALUES ('X0523821F','BJORN IRON SIDE ','VALHALA 127','0987654321','TACOS_DE_AZADA@GMAIL.COM')
INTO CLIENTE (DNI,NOMBRE,DIRECCION,TELEFONO,CORREO) VALUES ('T0523821F','NEFERTITI MORNING STAR','EL CAIRO 123','1122334455','TACOS_AL_PASTOR@GMAIL.COM')
SELECT* FROM DUAL;
SELECT * FROM CLIENTE;
DESCRIBE PROCURADOR;
INSERT ALL
INTO PROCURADOR (DNI,NOMBRE,DIRECCION,TELEFONO,CORREO) VALUES ('00524851F','ARMANDO ARCHUNDIA ','ACAPULCO 123','5544332211','HEY_SOY_ARMANDO@GMAIL.COM')
INTO PROCURADOR (DNI,NOMBRE,DIRECCION,TELEFONO,CORREO) VALUES ('X0412343F','CHUCK NORRIS','HOLLIWOOD 1234','1133557799','HI_IM_CHUCK@GMAIL.COM')
INTO PROCURADOR (DNI,NOMBRE,DIRECCION,TELEFONO,CORREO) VALUES ('T5234423F','SLATAN HIVARAHIMOVICH','MIAMI ASD 123','2244668800','WHATASHIWHASLAT@GMAIL.COM')
SELECT* FROM DUAL;
SELECT * FROM PROCURADOR;

DESCRIBE ASUNTOS;
INSERT ALL
INTO ASUNTOS (DNI_CLIENTE,DNI_PROCURADOR,FECHA_DE_INCIO,FECHA_DE_FINALIZACION,ESTADO) VALUES ('00523821F','00524851F','24/MAY/1990','25/MAY/1991','FINALIZADO')
INTO ASUNTOS (DNI_CLIENTE,DNI_PROCURADOR,FECHA_DE_INCIO,FECHA_DE_FINALIZACION,ESTADO) VALUES ('X0523821F','00524851F','24/MAY/1999','25/MAY/1992','FINALIZADO')
INTO ASUNTOS (DNI_CLIENTE,DNI_PROCURADOR,FECHA_DE_INCIO,FECHA_DE_FINALIZACION,ESTADO) VALUES ('T0523821F','00524851F','24/MAY/1999','','EN TRAMITE')
SELECT* FROM DUAL;
DESC

ALTER TABLE ASUNTOS MODIFY NUMERO_DE_EXPEDIENTE NUMBER PRIMARY KEY;
SELECT*FROM ASUNTOS;
commit;
INSERT ALL

INTO ASUNTOS (DNI_CLIENTE,DNI_PROCURADOR,FECHA_DE_INCIO,FECHA_DE_FINALIZACION,ESTADO) VALUES ('X0412343F','00524851F','24/MAY/1990','25/MAY/1991','INICIADO')
SELECT* FROM DUAL;


CREATE TABLE ASUNTO_PROCURADOR(
ID_AP NUMBER PRIMARY KEY,
NUMERO_DE_EXPEDIENTE NUMBER,
DNI_PROCURADOR NVARCHAR2(10),
CONSTRAINT fk_NUMERO_DE_EXPEDIENTE_P FOREIGN KEY (NUMERO_DE_EXPEDIENTE) REFERENCES ASUNTOS (NUMERO_DE_EXPEDIENTE),
CONSTRAINT fk_DNI_PROCURADOR_P FOREIGN KEY (DNI_PROCURADOR) REFERENCES PROCURADOR (DNI)
);

CREATE SEQUENCE ASUNTO_PROCURADOR_SEQ;
CREATE OR REPLACE TRIGGER INSERT_ASUNTO_PROCURADOR BEFORE 
INSERT ON ASUNTO_PROCURADOR FOR EACH ROW BEGIN
SELECT ASUNTO_PROCURADOR_SEQ.NEXTVAL INTO :new.ID_AP FROM dual;
END;

INSERT ALL

INTO ASUNTO_PROCURADOR (ID_AP,NUMERO_DE_EXPEDIENTE,DNI_PROCURADOR) VALUES (1,22,'00524851F')
INTO ASUNTO_PROCURADOR (ID_AP,NUMERO_DE_EXPEDIENTE,DNI_PROCURADOR) VALUES (2,22,'X0412343F')
INTO ASUNTO_PROCURADOR (ID_AP,NUMERO_DE_EXPEDIENTE,DNI_PROCURADOR) VALUES (3,22,'T0523821F')
SELECT* FROM DUAL;
select* from cliente;
select * from asuntos;
SELECT * FROM ASUNTO_PROCURADOR;
SELECT* FROM PROCURADOR;



----ejercicio 3---------------------------------------


create table SOCIO(
ID_SOCIO NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(40),
DIRECCION NVARCHAR2(40),
TELEFONO NVARCHAR2(10)
);

CREATE SEQUENCE SOCIO_SEQ;
CREATE TRIGGER INSERT_SOCIO
BEFORE INSERT ON SOCIO FOR EACH ROW BEGIN 
SELECT SOCIO_SEQ.NEXTVAL INTO:NEW.ID_SOCIO FROM DUAL;
END;

create table BARCO(
ID_BARCO NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(40),
NUMERO_AMARRE NUMBER,
CUOTA NUMBER(8,2)
);

CREATE SEQUENCE BARCO_SEQ;
CREATE TRIGGER INSERT_BARCO
BEFORE INSERT ON BARCO FOR EACH ROW BEGIN 
SELECT BARCO_SEQ.NEXTVAL INTO:NEW.ID_BARCO FROM DUAL;
END;

create table PATRON(
ID_PATRON NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(40),
DIRECCION NVARCHAR2(40),
TELEFONO NVARCHAR2(10)
);

CREATE SEQUENCE PATRON_SEQ;
CREATE TRIGGER INSERT_PATRON
BEFORE INSERT ON PATRON FOR EACH ROW BEGIN 
SELECT PATRON_SEQ.NEXTVAL INTO:NEW.ID_PATRON FROM DUAL;
END;

CREATE SEQUENCE TUTOR_SEQ;
CREATE TRIGGER INSERT_TUTOR
BEFORE INSERT ON TUTORES FOR EACH ROW BEGIN 
SELECT TUTOR_SEQ.NEXTVAL INTO:NEW.ID_TUTOR FROM DUAL;
END;


create table SOCIOS_BARCO(
ID_SB NUMBER PRIMARY KEY,
ID_SOCIO NUMBER,
ID_BARCO NUMBER,
CONSTRAINT FK_ID_SOCIO FOREIGN KEY (ID_SOCIO) REFERENCES SOCIO (ID_SOCIO),
CONSTRAINT FK_ID_BARCO FOREIGN KEY (ID_BARCO) REFERENCES BARCO (ID_BARCO)
);

CREATE SEQUENCE SOCIOS_BARCO_SEQ;
CREATE TRIGGER INSERT_SOCIOS_BARCO
BEFORE INSERT ON SOCIOS_BARCO FOR EACH ROW BEGIN 
SELECT SOCIOS_BARCO_SEQ.NEXTVAL INTO:NEW.ID_SB FROM DUAL;
END;


create table SALIDAS(
ID_SALIDAS NUMBER PRIMARY KEY,
DESTINO NVARCHAR2(39),
FECHA_SALIDA DATE,
ID_BARCO NUMBER,
ID_PATRON NUMBER,
CONSTRAINT FK_IDBARCO FOREIGN KEY (ID_BARCO) REFERENCES BARCO (ID_BARCO),
CONSTRAINT FK_IDPATRON FOREIGN KEY (ID_PATRON) REFERENCES PATRON (ID_PATRON)
);
CREATE SEQUENCE SALIDAS_SEQ;
CREATE TRIGGER INSERT_SALIDAS
BEFORE INSERT ON SALIDAS FOR EACH ROW BEGIN 
SELECT SALIDAS_SEQ.NEXTVAL INTO:NEW.ID_SALIDAS FROM DUAL;
END;

DESCRIBE SOCIO;
INSERT ALL 
INTO SOCIO (NOMBRE,DIRECCION,TELEFONO)VALUES('ESMERALDA','ACAPULCO','7441323459')
INTO SOCIO (NOMBRE,DIRECCION,TELEFONO)VALUES('JOSE DAVID','CHIAPAS','1235434566')    
INTO SOCIO (NOMBRE,DIRECCION,TELEFONO)VALUES('JONATHAN ','CHIAPAS','2346543678')  
INTO SOCIO (NOMBRE,DIRECCION,TELEFONO)VALUES('ANTONIO','EDO MEX','1232223435')  
INTO SOCIO (NOMBRE,DIRECCION,TELEFONO)VALUES('ALEX','EDO MEX','5552344562')  
SELECT * FROM DUAL;

INSERT ALL 
INTO PATRON (NOMBRE,DIRECCION,TELEFONO)VALUES('JUAN PABLO','MORELOS','5552345670')
INTO PATRON (NOMBRE,DIRECCION,TELEFONO)VALUES('MARICELA','EDO MEX','2221233456')    
INTO PATRON (NOMBRE,DIRECCION,TELEFONO)VALUES('ALFONZO ','EDO MEX','1233454222')  
INTO PATRON (NOMBRE,DIRECCION,TELEFONO)VALUES('JUAN ','VERACRUZ','224123524')  
INTO PATRON (NOMBRE,DIRECCION,TELEFONO)VALUES('RAFAEL','QUERETARO','2225432345')  
SELECT * FROM DUAL;


DESCRIBE BARCO;
INSERT ALL 
INTO BARCO (NOMBRE,NUMERO_AMARRE,CUOTA)VALUES('LA NIÑA',101,1200.50)
INTO BARCO (NOMBRE,NUMERO_AMARRE,CUOTA)VALUES('LA PINTA',102,1800.50)
INTO BARCO (NOMBRE,NUMERO_AMARRE,CUOTA)VALUES('LA SANTA MARIA ',103,2000.5)
INTO BARCO (NOMBRE,NUMERO_AMARRE,CUOTA)VALUES('PERLA NEGRA',104,5500.5)
INTO BARCO (NOMBRE,NUMERO_AMARRE,CUOTA)VALUES('EL HOLANDEZ',105,3200.5)
SELECT * FROM DUAL;

DESCRIBE SOCIOS_BARCO;
INSERT ALL 
INTO SOCIOS_BARCO (ID_SOCIO,ID_BARCO)VALUES(1,5)
INTO SOCIOS_BARCO (ID_SOCIO,ID_BARCO)VALUES(2,4)
INTO SOCIOS_BARCO (ID_SOCIO,ID_BARCO)VALUES(3,3)
INTO SOCIOS_BARCO (ID_SOCIO,ID_BARCO)VALUES(4,2)
INTO SOCIOS_BARCO (ID_SOCIO,ID_BARCO)VALUES(5,1)

SELECT * FROM DUAL;

SELECT* FROM salidas;
COMMIT;
INSERT ALL 
INTO SALIDAS (DESTINO,FECHA_SALIDA,ID_BARCO,ID_PATRON)VALUES('VERACRUZ',TO_DATE ('16/06/2023 08:00:00','DD-MM-YYYY HH24:MI:SS'),1,1)
INTO SALIDAS (DESTINO,FECHA_SALIDA,ID_BARCO,ID_PATRON)VALUES('VILLAHERMOSA ',TO_DATE ('17/06/2023 08:30:00','DD-MM-YYYY HH24:MI:SS'),2,2)
INTO SALIDAS (DESTINO,FECHA_SALIDA,ID_BARCO,ID_PATRON)VALUES('CAMPECHE',TO_DATE ('18/06/2023 09:00:00','DD-MM-YYYY HH24:MI:SS'),3,3)
INTO SALIDAS (DESTINO,FECHA_SALIDA,ID_BARCO,ID_PATRON)VALUES('YUCATAN',TO_DATE ('19/06/2023 08:40:00','DD-MM-YYYY HH24:MI:SS'),4,4)
INTO SALIDAS (DESTINO,FECHA_SALIDA,ID_BARCO,ID_PATRON)VALUES('CANCUN',TO_DATE ('20/06/2023 10:00:00','DD-MM-YYYY HH24:MI:SS'),5,5)
SELECT * FROM DUAL;

SELECT ID_BARCO,NOMBRE FROM  BARCO WHERE CUOTA >3000 AND NOMBRE='PERLA NEGRA';
SELECT*FROM BARCO WHERE CUOTA BETWEEN 1000 AND 3000;
SELECT*FROM ALUMNOS WHERE NOMBRE LIKE 'E%';
SELECT count (ID_ALUMNO ),GENERO FROM ALUMNOS GROUP BY GENERO;


select count(genero),genero from alumnos group by genero;

select * from barco;
select* from alumnos;
select * from patron;

select  ALUMNOS.(COUNT(NOMBRE) AS NOMBRES_ALUMNOS) , PATRON.(count(NOMBRE) AS NOMBRES_PATRON ) FROM ALUMNOS  A, patron  B; --group by id_patron;

select * from patron;
select count(NOMBRE).A  from alumnos A;
select count(id_barco) from barco;
select * from ALUMNOS;

--EJERCICIO CONSULTA DE DATOS
--BUSCAR LOS DATOS DEL PATRON QUE HAYA ESTADO EN LA SALIDA CON EL BARCO PERTENECIENTE AL SOCIO 1

select* from patron;
select* from barco;
select* from socio;
select* from salidas;
select* from socioS_BARCO;

select DISTINCT A.ID_PATRON,A.NOMBRE,A.DIRECCION, A.TELEFONO 
from patron A, SOCIOS_BARCO B, SALIDAS C,BARCO  D, SOCIO E 
WHERE e.id_socio=1 
AND e.id_socio= b.id_socio 
AND c.id_barco=b.id_barco
and a.id_patron=c.id_patron
;

--tambien  puede ser:
SELECT * FROM PATRON 
WHERE ID_PATRON IN --o podemos sustituir in por=
(SELECT ID_PATRON FROM SALIDAS WHERE ID_BARCO IN 
(SELECT ID_BARCO FROM SOCIOS_BARCO WHERE ID_SOCIO= 1));




---INNER JOIN
Select * from ALUMNOS A
inner JOIN CARRERAS_ALUMNOS CA
ON A.ID_ALUMNO= CA.ID_ALUMNO
INNER JOIN CARRERA C
ON CA.ID_CARRERA= C.ID_CARRERA;


---LEFT JOIN
Select * from ALUMNOS A
LEFT JOIN CARRERAS_ALUMNOS CA
ON A.ID_ALUMNO= CA.ID_ALUMNO;
--RIGTH JOIN

Select * from ALUMNOS A
RIGHT JOIN CARRERAS_ALUMNOS CA
ON A.ID_ALUMNO= CA.ID_ALUMNO;
-- FULL JOIN 
Select * from ALUMNOS A
FULL JOIN CARRERAS_ALUMNOS CA
ON A.ID_ALUMNO= CA.ID_ALUMNO;
SELECT * FROM CARRERAS_ALUMNOS;
SELECT * FROM CARRERA;
--- RESOLVIENDO EL EJERCICIO DEL BARCO SOCIO 1


SELECT * FROM PATRON P
INNER JOIN SALIDAS S
ON p.id_patron=s.id_patron
INNER JOIN  SOCIOS_BARCO SB
ON sb.id_barco=s.id_barco
WHERE sb.id_socio=1;


COMMIT;